version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.backend
    container_name: backend_app
    env_file:
      - ./backend/.env
    environment:
      CHOKIDAR_USEPOLLING: true 
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.frontend
    container_name: frontend_app
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
